# 1. Perkenalan Dataset
Tahap pertama, mencari dan menggunakan dataset pelanggan (Churn).

# 2. Import Library
Mengimpor beberapa pustaka (library) Python.

In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder

# 3. Memuat Dataset
Memuat dataset format CSV menggunakan pustaka pandas.

In [2]:
input_file = r'../churn_raw/churn.csv'
df = pd.read_csv(input_file)
df.head()

,Age,Gender,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,56.0,Male,0,150871.92,3,1,0,91690.50,0
1,69.0,Male,1,169116.98,2,0,1,21226.65,0
2,46.0,Male,7,201247.25,2,0,1,114213.29,1
3,32.0,Female,2,67455.18,3,1,1,185872.41,1
4,60.0,Male,9,NaN,2,0,0,166173.97,0

# 4. Data Preprocessing
Menyiapkan dan membersihkan data.

In [3]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Balance'] = df['Balance'].fillna(df['Balance'].mean())

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

scaler = StandardScaler()
scaled_features = ['Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
df[scaled_features] = scaler.fit_transform(df[scaled_features])
df.head()

,Age,Gender,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0.820855,1,-1.562439,3.741701e-01,1.198803,1,0,-0.345673,0
1,1.695681,1,-1.211723,6.298463e-01,-0.019493,0,1,-1.710998,0
2,0.147913,1,0.892572,1.080102e+00,-0.019493,0,1,0.090734,1
3,-0.794207,0,-0.861007,-7.947861e-01,1.198803,1,1,1.479219,1
4,1.090032,1,1.594004,-2.039225e-16,-0.019493,0,0,1.097537,0

# 5. Menyimpan Data
Simpan dataset yang telah melalui tahap preprocessing.

In [4]:
output_dir = 'churn_preprocessing'
os.makedirs(output_dir, exist_ok=True)
df.to_csv(os.path.join(output_dir, 'churn_processed.csv'), index=False)
print('Data preprocessing saved!')

Data preprocessing saved!